export const test_data = [{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_game_total_over',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_game_total_over',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Over',
'full_name': 'Over 207.5',
'type': 'over',
'market_type': 'game_total',
'status': 'Active',
'line': 207.5,
'decimal_price': 1.91,
'odds': -110.0,
'for_against_flag': 1,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}},
{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_game_total_under',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_game_total_under',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Under',
'full_name': 'Under 207.5',
'type': 'under',
'market_type': 'game_total',
'status': 'Active',
'line': 207.5,
'decimal_price': 1.91,
'odds': -110.0,
'for_against_flag': 0,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}},
{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_moneyline_away',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_moneyline_away',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Away',
'full_name': 'Away Moneyline',
'type': 'away',
'market_type': 'moneyline',
'status': 'Active',
'line': 0,
'decimal_price': -140.0,
'odds': -140.0,
'for_against_flag': 1,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}},
{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_moneyline_home',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_moneyline_home',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Home',
'full_name': 'Home Moneyline',
'type': 'home',
'market_type': 'moneyline',
'status': 'Active',
'line': 0,
'decimal_price': 115.0,
'odds': 115.0,
'for_against_flag': 1,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}},
{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_spread_away',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_spread_away',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Away',
'full_name': 'Away -2.5',
'type': 'away',
'market_type': 'spread',
'status': 'Active',
'line': -2.5,
'decimal_price': -110.0,
'odds': -110.0,
'for_against_flag': 1,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}},
{'_id': '2024-05-26_dallas-mavericks_minnesota-timberwolves_spread_home',
'selectionID': '2024-05-26_dallas-mavericks_minnesota-timberwolves_spread_home',
'eventID': '2024-05-26_dallas-mavericks_minnesota-timberwolves',
'event_name': 'Dallas Mavericks @ Minnesota Timberwolves',
'date': '2024-05-26',
'name': 'Home',
'full_name': 'Home 2.5',
'type': 'home',
'market_type': 'spread',
'status': 'Active',
'line': 2.5,
'decimal_price': -110.0,
'odds': -110.0,
'for_against_flag': 1,
'event_meta': {'awayID': 'minnesota-timberwolves',
 'homeID': 'dallas-mavericks',
 'date': '2024-05-26'}}]